"""sync_models_with_db

Revision ID: 07d35bff1e8f
Revises: c6e40dc29ee7
Create Date: 2026-01-21 20:15:47.830929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07d35bff1e8f'
down_revision: Union[str, Sequence[str], None] = 'c6e40dc29ee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False, comment='作业ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('paper_id', sa.UUID(), nullable=True, comment='关联的论文ID'),
    sa.Column('job_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='作业类型(search/paper_chat/summary/mindmap/deep_research)'),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='作业状态(queued/running/blocked/succeeded/failed/canceled/expired)'),
    sa.Column('progress', sa.Integer(), nullable=False, comment='作业进度(0-100)'),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='作业当前阶段'),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='幂等键'),
    sa.Column('dependency_ids', sa.JSON(), nullable=True, comment='依赖作业ID列表(JSON数组)'),
    sa.Column('payload', sa.JSON(), nullable=True, comment='作业负载(JSON对象)'),
    sa.Column('result_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='结果引用'),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='错误信息'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='作业表: 存储异步任务信息'
    )
    op.create_index(op.f('ix_jobs_idempotency_key'), 'jobs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_jobs_paper_id'), 'jobs', ['paper_id'], unique=False)
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.add_column('agent_sessions', sa.Column('paper_id', sa.UUID(), nullable=True, comment='关联论文ID(可选)'))
    op.add_column('agent_sessions', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='会话标题'))
    op.create_index(op.f('ix_agent_sessions_paper_id'), 'agent_sessions', ['paper_id'], unique=False)
    op.drop_constraint(op.f('agent_sessions_chat_session_id_fkey'), 'agent_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'agent_sessions', 'papers', ['paper_id'], ['id'])
    op.drop_column('agent_sessions', 'chat_session_id')
    op.drop_column('agent_sessions', 'interrupt_data')
    op.drop_column('agent_sessions', 'interrupt_type')
    op.drop_column('agent_sessions', 'completed_at')
    op.drop_table('user_config_values')
    op.drop_table('agent_checkpoint_writes')
    op.drop_index(op.f('ix_config_definitions_key'), table_name='config_definitions')
    op.drop_table('config_definitions')
    op.drop_index(op.f('ix_config_categories_code'), table_name='config_categories')
    op.drop_table('config_categories')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_agent_todos_agent_session_id'), table_name='agent_todos')
    op.drop_table('agent_todos')
    op.drop_table('agent_checkpoints')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.add_column('annotations', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()'), comment='更新时间'))
    op.add_column('collection_papers', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()'), comment='更新时间'))
    op.drop_index(op.f('uq_collections_user_default'), table_name='collections', postgresql_where='is_default')
    op.drop_column('collections', 'description')
    op.add_column('layers', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()'), comment='更新时间'))
    op.add_column('mind_maps', sa.Column('schema_version', sa.Integer(), nullable=False, server_default='1', comment='图数据 schema 版本'))
    op.add_column('mind_maps', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='ready', comment='状态(ready/archived)'))
    op.add_column('notes', sa.Column('page', sa.Integer(), nullable=True, comment='笔记对应的页码'))
    op.add_column('notes', sa.Column('tags', sa.JSON(), nullable=True, comment='标签(JSON数组)'))
    op.alter_column('notes', 'paper_id',
               existing_type=sa.UUID(),
               comment='关联论文ID',
               existing_comment='所属论文ID',
               existing_nullable=False)
    op.alter_column('notes', 'user_id',
               existing_type=sa.UUID(),
               comment='所属用户ID',
               existing_comment='创建者用户ID',
               existing_nullable=False)
    op.create_table_comment(
        'notes',
        '笔记表: 存储用户对论文的个人注释',
        existing_comment='用户笔记表: 存储论文层面的通用笔记',
        schema=None
    )
    op.add_column('paper_chunks', sa.Column('embedding_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='text-embedding-3-small', comment='用于生成Embedding的模型'))
    op.add_column('paper_chunks', sa.Column('embedding_dim', sa.Integer(), nullable=False, server_default='1536', comment='Embedding向量维度'))
    op.alter_column('paper_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               comment='向量Embedding(默认1536维)',
               existing_comment='向量Embedding(1536维)',
               existing_nullable=True)
    op.add_column('paper_summaries', sa.Column('version', sa.Integer(), nullable=False, server_default='1', comment='摘要版本号'))
    op.add_column('paper_summaries', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()'), comment='更新时间'))
    op.create_index(op.f('ix_paper_summaries_paper_id'), 'paper_summaries', ['paper_id'], unique=False)
    op.add_column('papers', sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='文件来源类型(如arXiv、PDF等)'))
    op.add_column('papers', sa.Column('source_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='文件来源引用(如arXiv ID、PDF URL等)'))
    op.add_column('papers', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()'), comment='更新时间'))
    op.alter_column('papers', 'file_url',
               existing_type=sa.VARCHAR(),
               comment='文件访问URL(可选),若为本地的则为nginx代理的相对位置。给前端用的',
               existing_comment='文件访问URL(可选)',
               existing_nullable=True)
    op.add_column('reports', sa.Column('job_id', sa.UUID(), nullable=True, comment='关联任务ID(可选)'))
    op.add_column('reports', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()'), comment='更新时间'))
    op.create_index(op.f('ix_reports_job_id'), 'reports', ['job_id'], unique=False)
    op.create_foreign_key(None, 'reports', 'jobs', ['job_id'], ['id'])
    op.add_column('search_histories', sa.Column('session_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='default', comment='搜索关键词'))
    op.add_column('search_histories', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()'), comment='更新时间'))
    op.drop_index(op.f('ix_search_histories_query'), table_name='search_histories')
    op.create_index(op.f('ix_search_histories_session_name'), 'search_histories', ['session_name'], unique=False)
    op.drop_column('search_histories', 'query')
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()'), comment='账号最后更新时间'))
    op.execute("UPDATE users SET settings = '{}' WHERE settings IS NULL")
    op.alter_column('users', 'settings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_comment='用户个性化设置')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'settings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_comment='用户个性化设置')
    op.drop_column('users', 'updated_at')
    op.add_column('search_histories', sa.Column('query', sa.VARCHAR(), autoincrement=False, nullable=False, comment='搜索关键词'))
    op.drop_index(op.f('ix_search_histories_session_name'), table_name='search_histories')
    op.create_index(op.f('ix_search_histories_query'), 'search_histories', ['query'], unique=False)
    op.drop_column('search_histories', 'updated_at')
    op.drop_column('search_histories', 'session_name')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_index(op.f('ix_reports_job_id'), table_name='reports')
    op.drop_column('reports', 'updated_at')
    op.drop_column('reports', 'job_id')
    op.alter_column('papers', 'file_url',
               existing_type=sa.VARCHAR(),
               comment='文件访问URL(可选)',
               existing_comment='文件访问URL(可选),若为本地的则为nginx代理的相对位置。给前端用的',
               existing_nullable=True)
    op.drop_column('papers', 'updated_at')
    op.drop_column('papers', 'source_ref')
    op.drop_column('papers', 'source_type')
    op.drop_index(op.f('ix_paper_summaries_paper_id'), table_name='paper_summaries')
    op.drop_column('paper_summaries', 'updated_at')
    op.drop_column('paper_summaries', 'version')
    op.alter_column('paper_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               comment='向量Embedding(1536维)',
               existing_comment='向量Embedding(默认1536维)',
               existing_nullable=True)
    op.drop_column('paper_chunks', 'embedding_dim')
    op.drop_column('paper_chunks', 'embedding_model')
    op.create_table_comment(
        'notes',
        '用户笔记表: 存储论文层面的通用笔记',
        existing_comment='笔记表: 存储用户对论文的个人注释',
        schema=None
    )
    op.alter_column('notes', 'user_id',
               existing_type=sa.UUID(),
               comment='创建者用户ID',
               existing_comment='所属用户ID',
               existing_nullable=False)
    op.alter_column('notes', 'paper_id',
               existing_type=sa.UUID(),
               comment='所属论文ID',
               existing_comment='关联论文ID',
               existing_nullable=False)
    op.drop_column('notes', 'tags')
    op.drop_column('notes', 'page')
    op.drop_column('mind_maps', 'status')
    op.drop_column('mind_maps', 'schema_version')
    op.drop_column('layers', 'updated_at')
    op.add_column('collections', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True, comment='描述'))
    op.create_index(op.f('uq_collections_user_default'), 'collections', ['user_id'], unique=True, postgresql_where='is_default')
    op.drop_column('collection_papers', 'updated_at')
    op.drop_column('annotations', 'updated_at')
    op.add_column('agent_sessions', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='完成时间'))
    op.add_column('agent_sessions', sa.Column('interrupt_type', sa.VARCHAR(), autoincrement=False, nullable=True, comment='中断类型(strong/weak)'))
    op.add_column('agent_sessions', sa.Column('interrupt_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='中断相关数据'))
    op.add_column('agent_sessions', sa.Column('chat_session_id', sa.UUID(), autoincrement=False, nullable=True, comment='关联的聊天会话ID'))
    op.drop_constraint(None, 'agent_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('agent_sessions_chat_session_id_fkey'), 'agent_sessions', 'chat_sessions', ['chat_session_id'], ['id'])
    op.drop_index(op.f('ix_agent_sessions_paper_id'), table_name='agent_sessions')
    op.drop_column('agent_sessions', 'title')
    op.drop_column('agent_sessions', 'paper_id')
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='会话ID'),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False, comment='所属用户ID'),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False, comment='会话标题'),
    sa.Column('agent_type', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Agent类型(chat/search/summary)'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('paper_id', sa.UUID(), autoincrement=False, nullable=True, comment='关联论文ID(可选)'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name='chat_sessions_paper_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='chat_sessions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chat_sessions_pkey'),
    comment='聊天会话表: 管理用户对话上下文',
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('agent_checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False, comment='线程ID'),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False, comment='检查点ID'),
    sa.Column('parent_id', sa.TEXT(), autoincrement=False, nullable=True, comment='父检查点ID'),
    sa.Column('checkpoint', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='检查点数据'),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='元数据'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('node_name', sa.VARCHAR(), autoincrement=False, nullable=True, comment='节点名称'),
    sa.Column('step_count', sa.INTEGER(), autoincrement=False, nullable=False, comment='步骤计数'),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_id', name=op.f('agent_checkpoints_pkey')),
    comment='Agent检查点表: 扩展LangGraph checkpoint'
    )
    op.create_table('agent_todos',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='待办ID'),
    sa.Column('agent_session_id', sa.UUID(), autoincrement=False, nullable=False, comment='Agent会话ID'),
    sa.Column('todo_type', sa.VARCHAR(), autoincrement=False, nullable=False, comment='待办类型(approval/input/selection等)'),
    sa.Column('todo_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='待办事项详情'),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False, comment='状态(pending/completed/cancelled)'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='完成时间'),
    sa.ForeignKeyConstraint(['agent_session_id'], ['agent_sessions.id'], name=op.f('agent_todos_agent_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_todos_pkey')),
    comment='Agent待办事项表: 存储弱人工介入的待办'
    )
    op.create_index(op.f('ix_agent_todos_agent_session_id'), 'agent_todos', ['agent_session_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='消息ID'),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False, comment='所属会话ID'),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False, comment='角色(user/assistant/system)'),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False, comment='消息内容'),
    sa.Column('sources', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='引用来源(JSON数组)'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='发送时间'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('chat_messages_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_messages_pkey')),
    comment='聊天消息表: 存储对话历史记录'
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('config_definitions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='配置定义ID'),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True, comment='关联的分类ID'),
    sa.Column('key', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='配置键(如 theme, timeout)'),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='配置显示名称'),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True, comment='配置描述'),
    sa.Column('value_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='值类型(string, number, boolean, json)'),
    sa.Column('default_value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='默认值(JSON格式)'),
    sa.Column('validation_rules', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='验证规则(JSON格式)'),
    sa.Column('options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='可选值列表(JSON格式)'),
    sa.Column('scope', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='作用域(system, user, session)'),
    sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='是否公开(前端可见)'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['category_id'], ['config_categories.id'], name='config_definitions_category_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='config_definitions_pkey'),
    sa.UniqueConstraint('category_id', 'key', name='unique_category_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='配置项定义表: 定义具体的配置项元数据',
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_config_definitions_key'), 'config_definitions', ['key'], unique=False)
    op.create_table('config_categories',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='分类ID'),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='分类代码(如 system.llm)'),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='分类显示名称'),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True, comment='分类描述'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id', name='config_categories_pkey'),
    comment='配置分类表: 用于对配置项进行分类管理',
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_config_categories_code'), 'config_categories', ['code'], unique=True)
    op.create_table('agent_checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False, comment='线程ID'),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False, comment='检查点ID'),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False, comment='任务ID'),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False, comment='索引'),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=True, comment='通道'),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True, comment='类型'),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True, comment='二进制数据'),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_id', 'task_id', 'idx', name=op.f('agent_checkpoint_writes_pkey')),
    comment='Agent检查点写入表: 扩展LangGraph checkpoint_writes'
    )
    op.create_table('user_config_values',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='配置值ID'),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False, comment='关联的用户ID'),
    sa.Column('config_id', sa.UUID(), autoincrement=False, nullable=False, comment='关联的配置定义ID'),
    sa.Column('value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='配置值(JSON格式)'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['config_id'], ['config_definitions.id'], name=op.f('user_config_values_config_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_config_values_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_config_values_pkey')),
    sa.UniqueConstraint('user_id', 'config_id', name=op.f('unique_user_config'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='用户配置值表: 存储用户特定的配置值'
    )
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_paper_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_idempotency_key'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
