"""add model_name to system_model_config

Revision ID: 2008ce6d0cfb
Revises: 6a99d68b5c03
Create Date: 2026-04-04 18:20:31.115513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '2008ce6d0cfb'
down_revision: Union[str, Sequence[str], None] = '6a99d68b5c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_model_configs', 'model_name',
               existing_type=sa.VARCHAR(),
               comment='模型名称 (Model Name)',
               existing_comment='模型名称',
               existing_nullable=False)
    op.alter_column('system_model_configs', 'api_key',
               existing_type=sa.VARCHAR(),
               comment='LLM API Key',
               existing_comment='API 密钥',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_model_configs', 'api_key',
               existing_type=sa.VARCHAR(),
               comment='API 密钥',
               existing_comment='LLM API Key',
               existing_nullable=False)
    op.alter_column('system_model_configs', 'model_name',
               existing_type=sa.VARCHAR(),
               comment='模型名称',
               existing_comment='模型名称 (Model Name)',
               existing_nullable=False)
    # ### end Alembic commands ###
