"""merge_entities_add_agent_tables

Revision ID: 555e29c4540c
Revises: ee0ffe641b9b
Create Date: 2026-01-14 21:02:28.175871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '555e29c4540c'
down_revision: Union[str, Sequence[str], None] = 'ee0ffe641b9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_checkpoint_writes',
    sa.Column('thread_id', sa.Text(), nullable=False, comment='线程ID'),
    sa.Column('checkpoint_id', sa.Text(), nullable=False, comment='检查点ID'),
    sa.Column('task_id', sa.Text(), nullable=False, comment='任务ID'),
    sa.Column('idx', sa.Integer(), nullable=False, comment='索引'),
    sa.Column('channel', sa.Text(), nullable=True, comment='通道'),
    sa.Column('type', sa.Text(), nullable=True, comment='类型'),
    sa.Column('blob', sa.LargeBinary(), nullable=True, comment='二进制数据'),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_id', 'task_id', 'idx'),
    comment='Agent检查点写入表: 扩展LangGraph checkpoint_writes'
    )
    op.create_table('agent_checkpoints',
    sa.Column('thread_id', sa.Text(), nullable=False, comment='线程ID'),
    sa.Column('checkpoint_id', sa.Text(), nullable=False, comment='检查点ID'),
    sa.Column('parent_id', sa.Text(), nullable=True, comment='父检查点ID'),
    sa.Column('checkpoint', sa.JSON(), nullable=True, comment='检查点数据'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='元数据'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('node_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='节点名称'),
    sa.Column('step_count', sa.Integer(), nullable=False, comment='步骤计数'),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_id'),
    comment='Agent检查点表: 扩展LangGraph checkpoint'
    )
    op.create_table('agent_sessions',
    sa.Column('id', sa.UUID(), nullable=False, comment='会话ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('chat_session_id', sa.UUID(), nullable=True, comment='关联的聊天会话ID'),
    sa.Column('thread_id', sa.Text(), nullable=True, comment='LangGraph线程ID'),
    sa.Column('agent_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Agent类型(search/paper_chat/summary/mindmap/deep_research)'),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='会话状态(active/interrupted/completed/error)'),
    sa.Column('interrupt_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='中断类型(strong/weak)'),
    sa.Column('interrupt_data', sa.JSON(), nullable=True, comment='中断相关数据'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Agent会话表: 存储Agent运行实例信息'
    )
    op.create_index(op.f('ix_agent_sessions_thread_id'), 'agent_sessions', ['thread_id'], unique=True)
    op.create_index(op.f('ix_agent_sessions_user_id'), 'agent_sessions', ['user_id'], unique=False)
    op.create_table('agent_todos',
    sa.Column('id', sa.UUID(), nullable=False, comment='待办ID'),
    sa.Column('agent_session_id', sa.UUID(), nullable=False, comment='Agent会话ID'),
    sa.Column('todo_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='待办类型(approval/input/selection等)'),
    sa.Column('todo_data', sa.JSON(), nullable=True, comment='待办事项详情'),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='状态(pending/completed/cancelled)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.ForeignKeyConstraint(['agent_session_id'], ['agent_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Agent待办事项表: 存储弱人工介入的待办'
    )
    op.create_index(op.f('ix_agent_todos_agent_session_id'), 'agent_todos', ['agent_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_todos_agent_session_id'), table_name='agent_todos')
    op.drop_table('agent_todos')
    op.drop_index(op.f('ix_agent_sessions_user_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_thread_id'), table_name='agent_sessions')
    op.drop_table('agent_sessions')
    op.drop_table('agent_checkpoints')
    op.drop_table('agent_checkpoint_writes')
    # ### end Alembic commands ###
