"""add_full_text_to_paper

Revision ID: 5f2af5ee2854
Revises: 44275d33ab4b
Create Date: 2026-01-22 20:52:08.631008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '5f2af5ee2854'
down_revision: Union[str, Sequence[str], None] = '44275d33ab4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('full_text', sa.Text(), nullable=True, comment='解析后的全文内容'))
    op.alter_column('papers', 'analysis_status',
               existing_type=sa.VARCHAR(),
               comment='分析状态(pending/processing/completed/failed)',
               existing_comment='分析状态(unprocessed/processing/processed/error)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('papers', 'analysis_status',
               existing_type=sa.VARCHAR(),
               comment='分析状态(unprocessed/processing/processed/error)',
               existing_comment='分析状态(pending/processing/completed/failed)',
               existing_nullable=False)
    op.drop_column('papers', 'full_text')
    # ### end Alembic commands ###
