"""add system_model_config table

Revision ID: 6a99d68b5c03
Revises: 9f33a9d10732
Create Date: 2026-04-04 16:13:48.694830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '6a99d68b5c03'
down_revision: Union[str, Sequence[str], None] = '9f33a9d10732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_model_configs',
    sa.Column('id', sa.UUID(), nullable=False, comment='配置唯一标识'),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='配置类型 (chat, summary, mind_map)'),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='模型供应商 (openai, siliconflow, ollama, etc.)'),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='模型名称'),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='接口基础地址'),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='API 密钥'),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='系统提示词 (System Prompt)'),
    sa.Column('temperature', sa.Float(), nullable=False, comment='模型采样温度'),
    sa.Column('max_tokens', sa.Integer(), nullable=False, comment='最大生成长度'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活该配置'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最后更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='全系统模型配置表: 存储默认 LLM 供应商及参数'
    )
    op.create_index(op.f('ix_system_model_configs_type'), 'system_model_configs', ['type'], unique=True)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='是否为系统管理员',
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='是否为系统管理员',
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_system_model_configs_type'), table_name='system_model_configs')
    op.drop_table('system_model_configs')
    # ### end Alembic commands ###
