"""initial_migration

Revision ID: 72747a6087ee
Revises: 
Create Date: 2026-01-21 23:37:21.604780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
import common.db_types
from service.setting.schema import Settings


# revision identifiers, used by Alembic.
revision: str = '72747a6087ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='用户全局唯一标识(UUID)'),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='用户邮箱(登录账号)'),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='加密后的密码哈希值'),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='用户全名/昵称'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='账号是否激活(True:激活, False:禁用/删除)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='账号创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='账号最后更新时间'),
    sa.Column('settings', common.db_types.PydanticJSON(Settings), nullable=False, comment='用户个性化设置'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户表: 存储系统用户的基本信息、认证凭据及状态'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('collections',
    sa.Column('collection_id', sa.UUID(), nullable=False, comment='收藏夹ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='所属用户ID'),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='收藏夹名称'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否为默认收藏夹'),
    sa.Column('total', sa.Integer(), nullable=False, comment='收藏夹下的论文数量'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('collection_id'),
    comment='收藏夹表: 用户自定义的论文集合'
    )
    op.create_index(op.f('ix_collections_is_default'), 'collections', ['is_default'], unique=False)
    op.create_index(op.f('ix_collections_name'), 'collections', ['name'], unique=False)
    op.create_index(op.f('ix_collections_user_id'), 'collections', ['user_id'], unique=False)
    op.create_table('papers',
    sa.Column('id', sa.UUID(), nullable=False, comment='论文全局唯一标识(UUID)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='所属用户ID'),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='论文标题'),
    sa.Column('authors', sa.JSON(), nullable=True, comment='作者列表(JSON数组)'),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='论文摘要原文'),
    sa.Column('toc', sa.JSON(), nullable=True, comment='论文目录结构(TOC)'),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='发表时间'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签(JSON数组)'),
    sa.Column('references_number', sa.Integer(), nullable=True, comment='引用数量'),
    sa.Column('file_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='文件存储Key/路径(MinIO或本地)'),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='文件访问URL(可选)'),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='文件来源类型(upload/web/arxiv)'),
    sa.Column('source_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='文件来源引用(如arXiv ID)'),
    sa.Column('analysis_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='分析状态(unprocessed/processing/processed/error)'),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='处理失败时的错误信息'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='上传/创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='论文表: 存储论文元数据、文件路径及处理状态'
    )
    op.create_index(op.f('ix_papers_analysis_status'), 'papers', ['analysis_status'], unique=False)
    op.create_index(op.f('ix_papers_title'), 'papers', ['title'], unique=False)
    op.create_index(op.f('ix_papers_user_id'), 'papers', ['user_id'], unique=False)
    op.create_table('search_histories',
    sa.Column('id', sa.UUID(), nullable=False, comment='记录ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='搜索关键词'),
    sa.Column('filters', sa.JSON(), nullable=True, comment='搜索过滤条件'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='搜索时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='搜索历史表'
    )
    op.create_index(op.f('ix_search_histories_query'), 'search_histories', ['query'], unique=False)
    op.create_index(op.f('ix_search_histories_user_id'), 'search_histories', ['user_id'], unique=False)
    op.create_table('agent_sessions',
    sa.Column('record_id', sa.UUID(), nullable=False, comment='记录ID(RecordID)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('paper_id', sa.UUID(), nullable=True, comment='关联论文ID(可选)'),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='会话标题'),
    sa.Column('thread_id', sa.Text(), nullable=True, comment='LangGraph线程ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('record_id'),
    comment='Agent会话表: 存储对话历史'
    )
    op.create_index(op.f('ix_agent_sessions_paper_id'), 'agent_sessions', ['paper_id'], unique=False)
    op.create_index(op.f('ix_agent_sessions_thread_id'), 'agent_sessions', ['thread_id'], unique=True)
    op.create_index(op.f('ix_agent_sessions_user_id'), 'agent_sessions', ['user_id'], unique=False)
    op.create_table('annotations',
    sa.Column('annotation_id', sa.UUID(), nullable=False, comment='标注ID'),
    sa.Column('paper_id', sa.UUID(), nullable=False, comment='所属论文ID'),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='标注类型(highlight/note/translate)'),
    sa.Column('rect', sa.JSON(), nullable=True, comment='标注区域坐标(JSON对象)'),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='标注内容(笔记/翻译结果)'),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='标注颜色(Hex/RGB)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('annotation_id'),
    comment='标注表: 存储PDF的高亮、笔记等标注信息'
    )
    op.create_index(op.f('ix_annotations_paper_id'), 'annotations', ['paper_id'], unique=False)
    op.create_table('collection_papers',
    sa.Column('collection_id', sa.UUID(), nullable=False, comment='收藏夹ID'),
    sa.Column('paper_id', sa.UUID(), nullable=False, comment='论文ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='收藏时间'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.collection_id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('collection_id', 'paper_id'),
    comment='收藏夹-论文关联表'
    )
    op.create_table('jobs',
    sa.Column('job_id', sa.UUID(), nullable=False, comment='作业ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('paper_id', sa.UUID(), nullable=True, comment='关联的论文ID'),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='任务类型'),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='任务状态'),
    sa.Column('progress', sa.Float(), nullable=False, comment='任务进度(0-1)'),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='当前阶段描述'),
    sa.Column('result', sa.JSON(), nullable=True, comment='任务产物(JSON)'),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='错误信息'),
    sa.Column('params_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='参数哈希(用于去重)'),
    sa.Column('pipeline_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='管道版本'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('end_at', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('job_id'),
    comment='任务表: 异步任务状态与结果'
    )
    op.create_index(op.f('ix_jobs_paper_id'), 'jobs', ['paper_id'], unique=False)
    op.create_index(op.f('ix_jobs_params_hash'), 'jobs', ['params_hash'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_type'), 'jobs', ['type'], unique=False)
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.create_table('mind_maps',
    sa.Column('id', sa.UUID(), nullable=False, comment='脑图ID'),
    sa.Column('paper_id', sa.UUID(), nullable=False, comment='所属论文ID'),
    sa.Column('graph_data', sa.JSON(), nullable=True, comment='图数据(JSON):包含nodes和edges'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='思维导图表: 存储论文的知识结构'
    )
    op.create_index(op.f('ix_mind_maps_paper_id'), 'mind_maps', ['paper_id'], unique=False)
    op.create_table('notes',
    sa.Column('note_id', sa.UUID(), nullable=False, comment='笔记ID'),
    sa.Column('paper_id', sa.UUID(), nullable=False, comment='关联论文ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='所属用户ID'),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='笔记标题'),
    sa.Column('page', sa.Integer(), nullable=True, comment='笔记对应的页码'),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='笔记内容(Markdown)'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签(JSON数组)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('note_id'),
    comment='笔记表: 存储用户对论文的个人注释'
    )
    op.create_index(op.f('ix_notes_paper_id'), 'notes', ['paper_id'], unique=False)
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_table('paper_chunks',
    sa.Column('id', sa.UUID(), nullable=False, comment='切片唯一标识'),
    sa.Column('paper_id', sa.UUID(), nullable=False, comment='所属论文ID'),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='切片文本内容'),
    sa.Column('page_number', sa.Integer(), nullable=True, comment='所在页码'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='切片顺序索引'),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True, comment='向量Embedding(默认1536维)'),
    sa.Column('embedding_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='用于生成Embedding的模型'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='论文切片表: 存储解析后的文本片段及向量Embedding'
    )
    op.create_index(op.f('ix_paper_chunks_paper_id'), 'paper_chunks', ['paper_id'], unique=False)
    op.create_table('paper_summaries',
    sa.Column('id', sa.UUID(), nullable=False, comment='摘要ID'),
    sa.Column('paper_id', sa.UUID(), nullable=False, comment='所属论文ID'),
    sa.Column('summary_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='摘要类型(如summary_config的key)'),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='摘要内容'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='生成时间'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='论文摘要表: 存储多维度的论文总结'
    )
    op.create_index(op.f('ix_paper_summaries_paper_id'), 'paper_summaries', ['paper_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_summaries_paper_id'), table_name='paper_summaries')
    op.drop_table('paper_summaries')
    op.drop_index(op.f('ix_paper_chunks_paper_id'), table_name='paper_chunks')
    op.drop_table('paper_chunks')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_paper_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_mind_maps_paper_id'), table_name='mind_maps')
    op.drop_table('mind_maps')
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_params_hash'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_paper_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('collection_papers')
    op.drop_index(op.f('ix_annotations_paper_id'), table_name='annotations')
    op.drop_table('annotations')
    op.drop_index(op.f('ix_agent_sessions_user_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_thread_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_paper_id'), table_name='agent_sessions')
    op.drop_table('agent_sessions')
    op.drop_index(op.f('ix_search_histories_user_id'), table_name='search_histories')
    op.drop_index(op.f('ix_search_histories_query'), table_name='search_histories')
    op.drop_table('search_histories')
    op.drop_index(op.f('ix_papers_user_id'), table_name='papers')
    op.drop_index(op.f('ix_papers_title'), table_name='papers')
    op.drop_index(op.f('ix_papers_analysis_status'), table_name='papers')
    op.drop_table('papers')
    op.drop_index(op.f('ix_collections_user_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_name'), table_name='collections')
    op.drop_index(op.f('ix_collections_is_default'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
