"""fix_pk_names

Revision ID: 7469a14abab5
Revises: 5f2af5ee2854
Create Date: 2026-01-25 01:14:42.901976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7469a14abab5'
down_revision: Union[str, Sequence[str], None] = '5f2af5ee2854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('checkpoint_migrations')
    # op.drop_index(op.f('checkpoint_writes_thread_id_idx'), table_name='checkpoint_writes')
    # op.drop_table('checkpoint_writes')
    # op.drop_index(op.f('checkpoints_thread_id_idx'), table_name='checkpoints')
    # op.drop_table('checkpoints')
    # op.drop_index(op.f('checkpoint_blobs_thread_id_idx'), table_name='checkpoint_blobs')
    # op.drop_table('checkpoint_blobs')

    # 1. AgentSession: record_id -> id
    op.add_column('agent_sessions', sa.Column('id', sa.UUID(), nullable=True, comment='记录ID(RecordID)'))
    op.execute("UPDATE agent_sessions SET id = record_id")
    op.alter_column('agent_sessions', 'id', nullable=False)
    op.execute("ALTER TABLE agent_sessions DROP CONSTRAINT IF EXISTS agent_sessions_pkey")
    op.drop_column('agent_sessions', 'record_id')
    op.create_primary_key("agent_sessions_pkey", "agent_sessions", ["id"])

    # 2. Jobs: job_id -> id
    op.add_column('jobs', sa.Column('id', sa.UUID(), nullable=True, comment='作业ID'))
    op.execute("UPDATE jobs SET id = job_id")
    op.alter_column('jobs', 'id', nullable=False)
    op.execute("ALTER TABLE jobs DROP CONSTRAINT IF EXISTS jobs_pkey")
    op.drop_column('jobs', 'job_id')
    op.create_primary_key("jobs_pkey", "jobs", ["id"])

    # 3. Notes: note_id -> id
    op.add_column('notes', sa.Column('id', sa.UUID(), nullable=True, comment='笔记ID'))
    op.execute("UPDATE notes SET id = note_id")
    op.alter_column('notes', 'id', nullable=False)
    op.execute("ALTER TABLE notes DROP CONSTRAINT IF EXISTS notes_pkey")
    op.drop_column('notes', 'note_id')
    op.create_primary_key("notes_pkey", "notes", ["id"])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Reverse Notes
    op.add_column('notes', sa.Column('note_id', sa.UUID(), autoincrement=False, nullable=True, comment='笔记ID'))
    op.execute("UPDATE notes SET note_id = id")
    op.alter_column('notes', 'note_id', nullable=False)
    op.execute("ALTER TABLE notes DROP CONSTRAINT IF EXISTS notes_pkey")
    op.drop_column('notes', 'id')
    op.create_primary_key("notes_pkey", "notes", ["note_id"])

    # Reverse Jobs
    op.add_column('jobs', sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=True, comment='作业ID'))
    op.execute("UPDATE jobs SET job_id = id")
    op.alter_column('jobs', 'job_id', nullable=False)
    op.execute("ALTER TABLE jobs DROP CONSTRAINT IF EXISTS jobs_pkey")
    op.drop_column('jobs', 'id')
    op.create_primary_key("jobs_pkey", "jobs", ["job_id"])

    # Reverse AgentSession
    op.add_column('agent_sessions', sa.Column('record_id', sa.UUID(), autoincrement=False, nullable=True, comment='记录ID(RecordID)'))
    op.execute("UPDATE agent_sessions SET record_id = id")
    op.alter_column('agent_sessions', 'record_id', nullable=False)
    op.execute("ALTER TABLE agent_sessions DROP CONSTRAINT IF EXISTS agent_sessions_pkey")
    op.drop_column('agent_sessions', 'id')
    op.create_primary_key("agent_sessions_pkey", "agent_sessions", ["record_id"])

    # Restore checkpoints (skipped implementation as we commented out drop)
    # op.create_table('checkpoint_blobs', ...)
    # ...
    # ### end Alembic commands ###
