"""add_db_comments

Revision ID: 7f00c08b09b7
Revises: 31e19415f3e2
Create Date: 2026-01-12 07:51:34.735605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f00c08b09b7'
down_revision: Union[str, Sequence[str], None] = '31e19415f3e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('annotations', 'id',
               existing_type=sa.UUID(),
               comment='标注ID',
               existing_nullable=False)
    op.alter_column('annotations', 'layer_id',
               existing_type=sa.UUID(),
               comment='所属图层ID',
               existing_nullable=False)
    op.alter_column('annotations', 'type',
               existing_type=sa.VARCHAR(),
               comment='标注类型(highlight/note/translate)',
               existing_nullable=False)
    op.alter_column('annotations', 'rects',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='标注区域坐标(JSON数组)',
               existing_nullable=True)
    op.alter_column('annotations', 'content',
               existing_type=sa.VARCHAR(),
               comment='标注内容(笔记/翻译结果)',
               existing_nullable=True)
    op.alter_column('annotations', 'color',
               existing_type=sa.VARCHAR(),
               comment='标注颜色(Hex/RGB)',
               existing_nullable=True)
    op.alter_column('annotations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=False)
    op.create_table_comment(
        'annotations',
        '标注表: 存储PDF的高亮、笔记等标注信息',
        existing_comment=None,
        schema=None
    )
    op.alter_column('chat_messages', 'id',
               existing_type=sa.UUID(),
               comment='消息ID',
               existing_nullable=False)
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.UUID(),
               comment='所属会话ID',
               existing_nullable=False)
    op.alter_column('chat_messages', 'role',
               existing_type=sa.VARCHAR(),
               comment='角色(user/assistant/system)',
               existing_nullable=False)
    op.alter_column('chat_messages', 'content',
               existing_type=sa.VARCHAR(),
               comment='消息内容',
               existing_nullable=False)
    op.alter_column('chat_messages', 'sources',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='引用来源(JSON数组)',
               existing_nullable=True)
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='发送时间',
               existing_nullable=False)
    op.create_table_comment(
        'chat_messages',
        '聊天消息表: 存储对话历史记录',
        existing_comment=None,
        schema=None
    )
    op.alter_column('chat_sessions', 'id',
               existing_type=sa.UUID(),
               comment='会话ID',
               existing_nullable=False)
    op.alter_column('chat_sessions', 'user_id',
               existing_type=sa.UUID(),
               comment='所属用户ID',
               existing_nullable=False)
    op.alter_column('chat_sessions', 'title',
               existing_type=sa.VARCHAR(),
               comment='会话标题',
               existing_nullable=False)
    op.alter_column('chat_sessions', 'agent_type',
               existing_type=sa.VARCHAR(),
               comment='Agent类型(chat/search/summary)',
               existing_nullable=False)
    op.alter_column('chat_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=False)
    op.create_table_comment(
        'chat_sessions',
        '聊天会话表: 管理用户对话上下文',
        existing_comment=None,
        schema=None
    )
    op.alter_column('layers', 'id',
               existing_type=sa.UUID(),
               comment='图层ID',
               existing_nullable=False)
    op.alter_column('layers', 'paper_id',
               existing_type=sa.UUID(),
               comment='所属论文ID',
               existing_nullable=False)
    op.alter_column('layers', 'user_id',
               existing_type=sa.UUID(),
               comment='创建者用户ID',
               existing_nullable=False)
    op.alter_column('layers', 'name',
               existing_type=sa.VARCHAR(),
               comment='图层名称',
               existing_nullable=False)
    op.alter_column('layers', 'type',
               existing_type=sa.VARCHAR(),
               comment='图层类型(user/system)',
               existing_nullable=False)
    op.alter_column('layers', 'visible',
               existing_type=sa.BOOLEAN(),
               comment='是否可见',
               existing_nullable=False)
    op.alter_column('layers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=False)
    op.create_table_comment(
        'layers',
        '阅读器图层表: 支持多层级标注管理',
        existing_comment=None,
        schema=None
    )
    op.alter_column('paper_chunks', 'id',
               existing_type=sa.UUID(),
               comment='切片唯一标识',
               existing_nullable=False)
    op.alter_column('paper_chunks', 'paper_id',
               existing_type=sa.UUID(),
               comment='所属论文ID',
               existing_nullable=False)
    op.alter_column('paper_chunks', 'content',
               existing_type=sa.VARCHAR(),
               comment='切片文本内容',
               existing_nullable=False)
    op.alter_column('paper_chunks', 'page_number',
               existing_type=sa.INTEGER(),
               comment='所在页码',
               existing_nullable=True)
    op.alter_column('paper_chunks', 'chunk_index',
               existing_type=sa.INTEGER(),
               comment='切片顺序索引',
               existing_nullable=False)
    op.alter_column('paper_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               comment='向量Embedding(1536维)',
               existing_nullable=True)
    op.create_table_comment(
        'paper_chunks',
        '论文切片表: 存储解析后的文本片段及向量Embedding',
        existing_comment=None,
        schema=None
    )
    op.alter_column('paper_summaries', 'id',
               existing_type=sa.UUID(),
               comment='摘要ID',
               existing_nullable=False)
    op.alter_column('paper_summaries', 'paper_id',
               existing_type=sa.UUID(),
               comment='所属论文ID',
               existing_nullable=False)
    op.alter_column('paper_summaries', 'summary_type',
               existing_type=sa.VARCHAR(),
               comment='摘要类型(如short, detailed, key_points)',
               existing_nullable=False)
    op.alter_column('paper_summaries', 'content',
               existing_type=sa.VARCHAR(),
               comment='摘要内容',
               existing_nullable=False)
    op.alter_column('paper_summaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='生成时间',
               existing_nullable=False)
    op.create_table_comment(
        'paper_summaries',
        '论文摘要表: 存储多维度的论文总结与分析',
        existing_comment=None,
        schema=None
    )
    op.alter_column('papers', 'id',
               existing_type=sa.UUID(),
               comment='论文全局唯一标识(UUID)',
               existing_nullable=False)
    op.alter_column('papers', 'user_id',
               existing_type=sa.UUID(),
               comment='所属用户ID',
               existing_nullable=False)
    op.alter_column('papers', 'title',
               existing_type=sa.VARCHAR(),
               comment='论文标题',
               existing_nullable=False)
    op.alter_column('papers', 'authors',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='作者列表(JSON数组)',
               existing_nullable=True)
    op.alter_column('papers', 'abstract',
               existing_type=sa.VARCHAR(),
               comment='论文摘要原文',
               existing_nullable=True)
    op.alter_column('papers', 'file_key',
               existing_type=sa.VARCHAR(),
               comment='文件存储Key/路径(MinIO或本地)',
               existing_nullable=False)
    op.alter_column('papers', 'file_url',
               existing_type=sa.VARCHAR(),
               comment='文件访问URL(可选)',
               existing_nullable=True)
    op.alter_column('papers', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='paperstatus'),
               comment='处理状态(PENDING/PROCESSING/COMPLETED/FAILED)',
               existing_nullable=False)
    op.alter_column('papers', 'error_message',
               existing_type=sa.VARCHAR(),
               comment='处理失败时的错误信息',
               existing_nullable=True)
    op.alter_column('papers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='上传/创建时间',
               existing_nullable=False)
    op.create_table_comment(
        'papers',
        '论文表: 存储论文元数据、文件路径及处理状态',
        existing_comment=None,
        schema=None
    )
    op.alter_column('reports', 'id',
               existing_type=sa.UUID(),
               comment='报告ID',
               existing_nullable=False)
    op.alter_column('reports', 'paper_id',
               existing_type=sa.UUID(),
               comment='基于的论文ID',
               existing_nullable=False)
    op.alter_column('reports', 'user_id',
               existing_type=sa.UUID(),
               comment='所属用户ID',
               existing_nullable=False)
    op.alter_column('reports', 'title',
               existing_type=sa.VARCHAR(),
               comment='报告标题',
               existing_nullable=False)
    op.alter_column('reports', 'type',
               existing_type=sa.VARCHAR(),
               comment='报告类型(deep_research/related_work)',
               existing_nullable=False)
    op.alter_column('reports', 'status',
               existing_type=sa.VARCHAR(),
               comment='生成状态(generating/completed/failed)',
               existing_nullable=False)
    op.alter_column('reports', 'content',
               existing_type=sa.VARCHAR(),
               comment='报告正文(Markdown)',
               existing_nullable=True)
    op.alter_column('reports', 'summary',
               existing_type=sa.VARCHAR(),
               comment='报告摘要',
               existing_nullable=True)
    op.alter_column('reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=False)
    op.create_table_comment(
        'reports',
        '研究报告表: 存储Agent生成的分析报告',
        existing_comment=None,
        schema=None
    )
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               comment='用户全局唯一标识(UUID)',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               comment='用户邮箱(登录账号)',
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               comment='加密后的密码哈希值',
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               comment='用户全名/昵称',
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='账号是否激活(True:激活, False:禁用/删除)',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='账号创建时间',
               existing_nullable=False)
    op.create_table_comment(
        'users',
        '用户表: 存储系统用户的基本信息、认证凭据及状态',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'users',
        existing_comment='用户表: 存储系统用户的基本信息、认证凭据及状态',
        schema=None
    )
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='账号创建时间',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='账号是否激活(True:激活, False:禁用/删除)',
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='用户全名/昵称',
               existing_nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='加密后的密码哈希值',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='用户邮箱(登录账号)',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='用户全局唯一标识(UUID)',
               existing_nullable=False)
    op.drop_table_comment(
        'reports',
        existing_comment='研究报告表: 存储Agent生成的分析报告',
        schema=None
    )
    op.alter_column('reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('reports', 'summary',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='报告摘要',
               existing_nullable=True)
    op.alter_column('reports', 'content',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='报告正文(Markdown)',
               existing_nullable=True)
    op.alter_column('reports', 'status',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='生成状态(generating/completed/failed)',
               existing_nullable=False)
    op.alter_column('reports', 'type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='报告类型(deep_research/related_work)',
               existing_nullable=False)
    op.alter_column('reports', 'title',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='报告标题',
               existing_nullable=False)
    op.alter_column('reports', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='所属用户ID',
               existing_nullable=False)
    op.alter_column('reports', 'paper_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='基于的论文ID',
               existing_nullable=False)
    op.alter_column('reports', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='报告ID',
               existing_nullable=False)
    op.drop_table_comment(
        'papers',
        existing_comment='论文表: 存储论文元数据、文件路径及处理状态',
        schema=None
    )
    op.alter_column('papers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='上传/创建时间',
               existing_nullable=False)
    op.alter_column('papers', 'error_message',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='处理失败时的错误信息',
               existing_nullable=True)
    op.alter_column('papers', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='paperstatus'),
               comment=None,
               existing_comment='处理状态(PENDING/PROCESSING/COMPLETED/FAILED)',
               existing_nullable=False)
    op.alter_column('papers', 'file_url',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='文件访问URL(可选)',
               existing_nullable=True)
    op.alter_column('papers', 'file_key',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='文件存储Key/路径(MinIO或本地)',
               existing_nullable=False)
    op.alter_column('papers', 'abstract',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='论文摘要原文',
               existing_nullable=True)
    op.alter_column('papers', 'authors',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='作者列表(JSON数组)',
               existing_nullable=True)
    op.alter_column('papers', 'title',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='论文标题',
               existing_nullable=False)
    op.alter_column('papers', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='所属用户ID',
               existing_nullable=False)
    op.alter_column('papers', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='论文全局唯一标识(UUID)',
               existing_nullable=False)
    op.drop_table_comment(
        'paper_summaries',
        existing_comment='论文摘要表: 存储多维度的论文总结与分析',
        schema=None
    )
    op.alter_column('paper_summaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='生成时间',
               existing_nullable=False)
    op.alter_column('paper_summaries', 'content',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='摘要内容',
               existing_nullable=False)
    op.alter_column('paper_summaries', 'summary_type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='摘要类型(如short, detailed, key_points)',
               existing_nullable=False)
    op.alter_column('paper_summaries', 'paper_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='所属论文ID',
               existing_nullable=False)
    op.alter_column('paper_summaries', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='摘要ID',
               existing_nullable=False)
    op.drop_table_comment(
        'paper_chunks',
        existing_comment='论文切片表: 存储解析后的文本片段及向量Embedding',
        schema=None
    )
    op.alter_column('paper_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               comment=None,
               existing_comment='向量Embedding(1536维)',
               existing_nullable=True)
    op.alter_column('paper_chunks', 'chunk_index',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='切片顺序索引',
               existing_nullable=False)
    op.alter_column('paper_chunks', 'page_number',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='所在页码',
               existing_nullable=True)
    op.alter_column('paper_chunks', 'content',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='切片文本内容',
               existing_nullable=False)
    op.alter_column('paper_chunks', 'paper_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='所属论文ID',
               existing_nullable=False)
    op.alter_column('paper_chunks', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='切片唯一标识',
               existing_nullable=False)
    op.drop_table_comment(
        'layers',
        existing_comment='阅读器图层表: 支持多层级标注管理',
        schema=None
    )
    op.alter_column('layers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('layers', 'visible',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否可见',
               existing_nullable=False)
    op.alter_column('layers', 'type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='图层类型(user/system)',
               existing_nullable=False)
    op.alter_column('layers', 'name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='图层名称',
               existing_nullable=False)
    op.alter_column('layers', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='创建者用户ID',
               existing_nullable=False)
    op.alter_column('layers', 'paper_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='所属论文ID',
               existing_nullable=False)
    op.alter_column('layers', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='图层ID',
               existing_nullable=False)
    op.drop_table_comment(
        'chat_sessions',
        existing_comment='聊天会话表: 管理用户对话上下文',
        schema=None
    )
    op.alter_column('chat_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('chat_sessions', 'agent_type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Agent类型(chat/search/summary)',
               existing_nullable=False)
    op.alter_column('chat_sessions', 'title',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='会话标题',
               existing_nullable=False)
    op.alter_column('chat_sessions', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='所属用户ID',
               existing_nullable=False)
    op.alter_column('chat_sessions', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='会话ID',
               existing_nullable=False)
    op.drop_table_comment(
        'chat_messages',
        existing_comment='聊天消息表: 存储对话历史记录',
        schema=None
    )
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='发送时间',
               existing_nullable=False)
    op.alter_column('chat_messages', 'sources',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='引用来源(JSON数组)',
               existing_nullable=True)
    op.alter_column('chat_messages', 'content',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='消息内容',
               existing_nullable=False)
    op.alter_column('chat_messages', 'role',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='角色(user/assistant/system)',
               existing_nullable=False)
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='所属会话ID',
               existing_nullable=False)
    op.alter_column('chat_messages', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='消息ID',
               existing_nullable=False)
    op.drop_table_comment(
        'annotations',
        existing_comment='标注表: 存储PDF的高亮、笔记等标注信息',
        schema=None
    )
    op.alter_column('annotations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('annotations', 'color',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='标注颜色(Hex/RGB)',
               existing_nullable=True)
    op.alter_column('annotations', 'content',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='标注内容(笔记/翻译结果)',
               existing_nullable=True)
    op.alter_column('annotations', 'rects',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='标注区域坐标(JSON数组)',
               existing_nullable=True)
    op.alter_column('annotations', 'type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='标注类型(highlight/note/translate)',
               existing_nullable=False)
    op.alter_column('annotations', 'layer_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='所属图层ID',
               existing_nullable=False)
    op.alter_column('annotations', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='标注ID',
               existing_nullable=False)
    # ### end Alembic commands ###
