"""add_search_history_table

Revision ID: 9cdd62d4f996
Revises: c8a8ffc4772a
Create Date: 2026-01-12 18:03:38.798549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '9cdd62d4f996'
down_revision: Union[str, Sequence[str], None] = 'c8a8ffc4772a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_histories',
    sa.Column('id', sa.UUID(), nullable=False, comment='记录ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='搜索关键词'),
    sa.Column('filters', sa.JSON(), nullable=True, comment='搜索过滤条件(JSON)'),
    sa.Column('result_count', sa.Integer(), nullable=False, comment='搜索结果数量'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='搜索时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='搜索历史表: 记录用户的搜索关键词及上下文'
    )
    op.create_index(op.f('ix_search_histories_query'), 'search_histories', ['query'], unique=False)
    op.create_index(op.f('ix_search_histories_user_id'), 'search_histories', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_histories_user_id'), table_name='search_histories')
    op.drop_index(op.f('ix_search_histories_query'), table_name='search_histories')
    op.drop_table('search_histories')
    # ### end Alembic commands ###
