"""Add search_api_configs table

Revision ID: 9f33a9d10732
Revises: 8323c615c12a
Create Date: 2026-04-02 09:29:37.045884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f33a9d10732'
down_revision: Union[str, Sequence[str], None] = '8323c615c12a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('search_api_configs', 'id',
               existing_type=sa.UUID(),
               comment='配置记录唯一标识',
               existing_comment='配置ID',
               existing_nullable=False)
    op.alter_column('search_api_configs', 'api_name',
               existing_type=sa.VARCHAR(),
               comment='接口平台名称(如 arXiv, Semantic Scholar)',
               existing_comment='接口标识名称(如arxiv, semantic_scholar)',
               existing_nullable=False)
    op.alter_column('search_api_configs', 'api_key',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment='API 密钥/凭据',
               existing_comment='接口调用的API Key(可选)')
    op.alter_column('search_api_configs', 'weight',
               existing_type=sa.INTEGER(),
               comment='搜索权重/优先级(权重越高越优先使用)',
               existing_comment='接口权重, 决定调用顺位(越大越优先)',
               existing_nullable=False)
    op.alter_column('search_api_configs', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否激活该数据源',
               existing_comment='是否启用此搜索源',
               existing_nullable=False)
    op.alter_column('search_api_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='最后更新时间',
               existing_comment='更新时间',
               existing_nullable=False)
    op.drop_index(op.f('ix_search_api_configs_weight'), table_name='search_api_configs')
    op.create_table_comment(
        'search_api_configs',
        '全局搜索源配置表: 存储 API 密钥、权重和激活状态',
        existing_comment='搜索API配置表: 存储搜索数据源的权重与开关',
        schema=None
    )
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='是否为系统管理员'))
    op.create_table_comment(
        'search_api_configs',
        '搜索API配置表: 存储搜索数据源的权重与开关',
        existing_comment='全局搜索源配置表: 存储 API 密钥、权重和激活状态',
        schema=None
    )
    op.create_index(op.f('ix_search_api_configs_weight'), 'search_api_configs', ['weight'], unique=False)
    op.alter_column('search_api_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新时间',
               existing_comment='最后更新时间',
               existing_nullable=False)
    op.alter_column('search_api_configs', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否启用此搜索源',
               existing_comment='是否激活该数据源',
               existing_nullable=False)
    op.alter_column('search_api_configs', 'weight',
               existing_type=sa.INTEGER(),
               comment='接口权重, 决定调用顺位(越大越优先)',
               existing_comment='搜索权重/优先级(权重越高越优先使用)',
               existing_nullable=False)
    op.alter_column('search_api_configs', 'api_key',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment='接口调用的API Key(可选)',
               existing_comment='API 密钥/凭据')
    op.alter_column('search_api_configs', 'api_name',
               existing_type=sa.VARCHAR(),
               comment='接口标识名称(如arxiv, semantic_scholar)',
               existing_comment='接口平台名称(如 arXiv, Semantic Scholar)',
               existing_nullable=False)
    op.alter_column('search_api_configs', 'id',
               existing_type=sa.UUID(),
               comment='配置ID',
               existing_comment='配置记录唯一标识',
               existing_nullable=False)
    # ### end Alembic commands ###
