"""add_collection_models

Revision ID: c8a8ffc4772a
Revises: 7f00c08b09b7
Create Date: 2026-01-12 17:33:19.447766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'c8a8ffc4772a'
down_revision: Union[str, Sequence[str], None] = '7f00c08b09b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.UUID(), nullable=False, comment='收藏夹ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='所属用户ID'),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='收藏夹名称'),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='描述'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='收藏夹表: 用户自定义的论文集合'
    )
    op.create_index(op.f('ix_collections_name'), 'collections', ['name'], unique=False)
    op.create_index(op.f('ix_collections_user_id'), 'collections', ['user_id'], unique=False)
    op.create_table('collection_papers',
    sa.Column('id', sa.UUID(), nullable=False, comment='关联ID'),
    sa.Column('collection_id', sa.UUID(), nullable=False, comment='收藏夹ID'),
    sa.Column('paper_id', sa.UUID(), nullable=False, comment='论文ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='收藏时间'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='收藏夹-论文关联表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_papers')
    op.drop_index(op.f('ix_collections_user_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_name'), table_name='collections')
    op.drop_table('collections')
    # ### end Alembic commands ###
