"""add_config_tables

Revision ID: ee0ffe641b9b
Revises: 9cdd62d4f996
Create Date: 2026-01-14 20:53:58.007591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'ee0ffe641b9b'
down_revision: Union[str, Sequence[str], None] = '9cdd62d4f996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_categories',
    sa.Column('id', sa.UUID(), nullable=False, comment='分类ID'),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False, comment='分类代码(如 system.llm)'),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False, comment='分类显示名称'),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='分类描述'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='配置分类表: 用于对配置项进行分类管理'
    )
    op.create_index(op.f('ix_config_categories_code'), 'config_categories', ['code'], unique=True)
    op.create_table('config_definitions',
    sa.Column('id', sa.UUID(), nullable=False, comment='配置定义ID'),
    sa.Column('category_id', sa.Uuid(), nullable=True, comment='关联的分类ID'),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False, comment='配置键(如 theme, timeout)'),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False, comment='配置显示名称'),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='配置描述'),
    sa.Column('value_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False, comment='值类型(string, number, boolean, json)'),
    sa.Column('default_value', sa.JSON(), nullable=True, comment='默认值(JSON格式)'),
    sa.Column('validation_rules', sa.JSON(), nullable=True, comment='验证规则(JSON格式)'),
    sa.Column('options', sa.JSON(), nullable=True, comment='可选值列表(JSON格式)'),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False, comment='作用域(system, user, session)'),
    sa.Column('is_public', sa.Boolean(), nullable=False, comment='是否公开(前端可见)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['category_id'], ['config_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'key', name='unique_category_key'),
    comment='配置项定义表: 定义具体的配置项元数据'
    )
    op.create_index(op.f('ix_config_definitions_key'), 'config_definitions', ['key'], unique=False)
    op.create_table('mind_maps',
    sa.Column('id', sa.UUID(), nullable=False, comment='脑图ID'),
    sa.Column('paper_id', sa.UUID(), nullable=False, comment='所属论文ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='所属用户ID'),
    sa.Column('graph_data', sa.JSON(), nullable=True, comment='图数据(JSON):包含nodes和edges'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='思维导图表: 存储论文的知识结构(节点与边)'
    )
    op.create_index(op.f('ix_mind_maps_paper_id'), 'mind_maps', ['paper_id'], unique=False)
    op.create_index(op.f('ix_mind_maps_user_id'), 'mind_maps', ['user_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.UUID(), nullable=False, comment='笔记ID'),
    sa.Column('paper_id', sa.UUID(), nullable=False, comment='所属论文ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='创建者用户ID'),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='笔记标题'),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='笔记内容(Markdown)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='用户笔记表: 存储论文层面的通用笔记'
    )
    op.create_index(op.f('ix_notes_paper_id'), 'notes', ['paper_id'], unique=False)
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_table('user_config_values',
    sa.Column('id', sa.UUID(), nullable=False, comment='配置值ID'),
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='关联的用户ID'),
    sa.Column('config_id', sa.Uuid(), nullable=False, comment='关联的配置定义ID'),
    sa.Column('value', sa.JSON(), nullable=False, comment='配置值(JSON格式)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['config_id'], ['config_definitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'config_id', name='unique_user_config'),
    comment='用户配置值表: 存储用户特定的配置值'
    )
    op.add_column('chat_sessions', sa.Column('paper_id', sa.UUID(), nullable=True, comment='关联论文ID(可选)'))
    op.create_foreign_key(None, 'chat_sessions', 'papers', ['paper_id'], ['id'])
    op.add_column('papers', sa.Column('toc', sa.JSON(), nullable=True, comment='论文目录结构(TOC)'))
    op.add_column('users', sa.Column('settings', sa.JSON(), nullable=True, comment='用户个性化设置'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'settings')
    op.drop_column('papers', 'toc')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'paper_id')
    op.drop_table('user_config_values')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_paper_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_mind_maps_user_id'), table_name='mind_maps')
    op.drop_index(op.f('ix_mind_maps_paper_id'), table_name='mind_maps')
    op.drop_table('mind_maps')
    op.drop_index(op.f('ix_config_definitions_key'), table_name='config_definitions')
    op.drop_table('config_definitions')
    op.drop_index(op.f('ix_config_categories_code'), table_name='config_categories')
    op.drop_table('config_categories')
    # ### end Alembic commands ###
